#Fonts and Chars
#font_family      JetBrains Mono Medium
font_family      FiraCode-Medium
bold_font        auto
italic_font      auto
bold_italic_font auto

font_size 13.0
font_features FiraCode-Medium +onum
disable_ligatures never

scrollback_lines 1000

shell .
editor .


#Color and opacity
foreground #fcfcfc
background #232627

#Black
color0 #232627
color8 #7f8c8d

#Red
color1 #ed1515
color9 #b30047

#Green
color2 #11d116
color10 #1cfc9a

#Yellow
color3 #f67400
color11 #fdbc4b

#Blue
color4 #3333ff
color12 #33ccff

#Magenta
color5 #9b59b6
color13 #8e44ad

#Cyan
color6 #1abc9c
color14 #16a085

#White
color7 #fcfcfc
color15 #ffffff

background_opacity 0.95

