#!/bin/zsh

export EDITOR="nvim"
export VISUAL="nvim"
export TERMINAL="kitty"
export BROWSER="Firefox"

export ZDOTDIR="${XDG_CONFIG_HOME:-$HOME/.config}/shell"
export XMONAD="${XDG_CONFIG_HOME:-$HOME/.config/xmonad}/.xmonad"
